language: node_js
node_js:
  - "12"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project instantmessagetest-148722 --token $FIREBASE_TOKEN