language: node_js
node_js:
  - "12"
script:
 - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project instantmessagetest-148722 --token 1//04z0vLRWnLhGgCgYIARAAGAQSNwF-L9IrAHzgxfHmyjkNIrSDifrUENifHbtm4QZWyH5-zox_uT2124JxmNl9oDCYa5_F_4cs66I --non-interactive